apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: telegraf
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - image: harbor.tanzu.moshahat.io/dockerhub/library/telegraf:1.16.2
          name: telegraf
          envFrom:
            - secretRef:
                name: telegraf-secrets
          volumeMounts:
            - name: telegraf-config-volume
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config