#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
  namespace: telegraf
  annotations:
    kapp.k14s.io/versioned: ""
data:
  